# Generated by Django 4.1.7 on 2023-10-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='loaction',
            new_name='location',
        ),
    ]
