# Generated by Django 4.1.7 on 2023-10-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume_bio_resume_cv_resume_facebook_resume_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('null', 'not specified'), ('M', 'male'), ('F', 'female')], default='null', max_length=50),
        ),
    ]
