# Generated by Django 4.1.7 on 2023-10-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_resume_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
