# Generated by Django 4.1.7 on 2023-10-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_resume_phone_number_alter_resume_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(default='Default.jpg', upload_to='resume/'),
        ),
    ]
