# Generated by Django 4.1.7 on 2023-10-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_remove_resume_skills_delete_skills_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
