# Generated by Django 4.2.5 on 2023-09-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('skills', models.TextField()),
                ('experience', models.IntegerField()),
                ('education', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='resumes')),
                ('gender', models.CharField(choices=[('male', 'male'), ('Female', 'female')], default='male', max_length=10)),
            ],
        ),
    ]
