# Generated by Django 4.2.5 on 2023-09-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='creater',
            new_name='createtd_by',
        ),
    ]
