# Generated by Django 4.1.7 on 2023-10-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_city_industry_job_job_type_job_city_job_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
    ]
