# Generated by Django 4.1.7 on 2023-10-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_remove_job_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyjob',
            old_name='status',
            new_name='job_status',
        ),
    ]
