# Generated by Django 4.1.7 on 2023-10-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_remove_applyjob_content_remove_applyjob_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
