# Generated by Django 4.1.7 on 2023-10-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_applyjob_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='experience',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
