# Generated by Django 4.1.7 on 2023-10-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_conversationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='applyjob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationmessages', to='job.applyjob'),
        ),
    ]
